# Generated by Django 5.1.2 on 2024-11-12 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='puntuacion',
            new_name='puntuacion_general',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factibilidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='impacto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='viabilidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('idea', 'usuario')},
        ),
    ]
