# Generated by Django 5.1.2 on 2024-11-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_rename_puntuacion_calificacion_puntuacion_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion_general',
            field=models.IntegerField(null=True),
        ),
    ]
