# Generated by Django 5.1.2 on 2024-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0003_alter_calificacion_puntuacion_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='prioridad',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='prioridad',
            name='usuario_asignador',
        ),
        migrations.AlterField(
            model_name='idea',
            name='tipo',
            field=models.CharField(choices=[('problema', 'Problema'), ('oportunidad', 'Oportunidad'), ('reto', 'Reto')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ArchivoAdjunto',
        ),
        migrations.DeleteModel(
            name='Estadistica',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
    ]
