# Generated by Django 5.1.2 on 2024-11-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0004_remove_estadistica_idea_remove_prioridad_idea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='propuestas.idea')),
            ],
            options={
                'db_table': 'archivo_adjunto',
            },
        ),
    ]
