# Generated by Django 5.1.2 on 2024-12-21 14:26

import django.db.models.deletion
import propuestas.utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0005_archivoadjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='tipo_calificacion',
            field=models.CharField(choices=[('encargado', 'Encargado'), ('gerente', 'Gerente')], default='encargado', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='encargado_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_a_revisar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='revisada_por_encargado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(upload_to=propuestas.utils.utils.simple_unique_file_path, validators=[propuestas.utils.utils.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='propuestas.idea'),
        ),
    ]
