# Generated by Django 5.1.2 on 2024-12-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0006_calificacion_tipo_calificacion_idea_encargado_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='calificacion_definitiva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='revisada_por_gerente',
            field=models.BooleanField(default=False),
        ),
    ]
