# Generated by Django 5.1.2 on 2024-12-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0007_idea_calificacion_definitiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='estado',
        ),
        migrations.AddField(
            model_name='idea',
            name='estado_ejecucion',
            field=models.CharField(choices=[('no_iniciada', 'No Iniciada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='no_iniciada', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada_parcialmente', 'Revisada Parcialmente'), ('revisada_completamente', 'Revisada Completamente'), ('denegada', 'Denegada'), ('neutra', 'Neutra'), ('aprobada', 'Aprobada')], default='pendiente', max_length=50),
        ),
    ]
