# Generated by Django 5.1.2 on 2024-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0008_remove_idea_estado_idea_estado_ejecucion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='encargado_area',
        ),
        migrations.AlterField(
            model_name='idea',
            name='estado_ejecucion',
            field=models.CharField(blank=True, choices=[('pendiente_ejecucion', 'Pendiente de Ejecución'), ('en_ejecucion', 'En Ejecución'), ('completada', 'Completada')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='estado_revision',
            field=models.CharField(choices=[('por_revisar', 'Por Revisar'), ('revisada_parcialmente', 'Revisada Parcialmente'), ('denegada', 'Denegada'), ('en_evaluacion_final', 'En Evaluación Final'), ('aprobada', 'Aprobada')], default='por_revisar', max_length=50),
        ),
    ]
