# Generated by Django 5.1.2 on 2024-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0009_remove_idea_encargado_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='calificacion_definitiva',
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factibilidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='impacto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion_general',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='viabilidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
