# Generated by Django 5.1.2 on 2024-12-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('propuestas', '0006_calificacion_tipo_calificacion_idea_encargado_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='area_encargada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado', to='propuestas.area'),
        ),
        migrations.AddField(
            model_name='account',
            name='es_gerente',
            field=models.BooleanField(default=False),
        ),
    ]
